a_core/urls.py
from django.contrib import admin
from django.urls import include, path
from a_contents.views import *

from django.conf import settings
from django.conf.urls.static import static

from a_users.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('content/type/<str:content_type>/', home_view, name='content-query'),
    # path('content/<str:content_type>/', content_query_view, name='content-query'),
    
    path('content/create/<str:content_type>/', content_create_view, name='content-create'),
    path('content/delete/<pk>/', content_delete_view, name='content-delete'),
    path('content/edit/<pk>/', content_edit_view, name='content-edit'),
    path('content/<pk>/', content_page_view, name='content'),
    path('content/<pk>/like', like_content, name='like-content'),
    path('content/download/<str:content_id>/', download_gallery_images, name='download-gallery-images'),
    path('comment/like/<pk>/', like_comment, name='like-comment'),
    path('reply/like/<pk>/', like_reply, name='like-reply'),
    
    path('profile/', profile_view, name='profile'),
    path('<str:username>/', profile_view, name='userprofile'),
    path('profile/edit/', profile_edit_view, name='profile-edit'),
    path('profile/delete/', profile_delete_view, name='profile-delete'),
    path('profile/onboarding/', profile_edit_view, name='profile-onboarding'),
    path('commentsent/<pk>/', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>/', comment_delete_view, name='comment-delete'),
    path('reply-sent/<pk>/', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>/', reply_delete_view, name='reply-delete'),
    
    #Ckeditor
    # path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="custom_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_contents/models.py
from django.db import models

from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from django.templatetags.static import static
import uuid

from embed_video.fields import EmbedVideoField
from django.core.validators import FileExtensionValidator


# Create your models here.
class Content(models.Model):
    class TypeChoices(models.TextChoices):
        VIDEO = 'V'
        GALLERY = 'G'
        ARTICLE = 'R'
        PROJECT = 'P'
        LESSON = 'L'
        EBOOK = 'E'
        APP = 'A'
        TEACHING_PLAN = 'T'
        
    class ApprovalStatus(models.TextChoices):
        PENDING = 'P', 'Pending'
        APPROVED = 'A', 'Approved'
        REJECTED = 'R', 'Rejected'
        
    title = models.CharField(max_length=500)
    type = models.CharField(max_length=1, choices=TypeChoices.choices)
    image = models.ImageField(upload_to='thumpnails/', null=True, blank=True) #ถ้าเชื่อได้ไวว่ามันเซฟไปที่มีเดียจริงๆก็ค่อยเป็นเป็น '/'
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='contents')
    description = models.TextField()
    
    likes = models.ManyToManyField(User, related_name="likecontents", through="LikedContent")
    view_count = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    grades = models.ManyToManyField('Grade')
    learning_areas = models.ManyToManyField('LearningArea')
    subject = models.CharField(max_length=500, null=True, blank=True)
    
    # Approval status field
    approval_status = models.CharField(max_length=1, choices=ApprovalStatus.choices, default=ApprovalStatus.PENDING)
    
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created']
        
    @property
    def thumbnail(self):
        try:
            thumbnail = self.image.url
        except:
            thumbnail = static('images/catbook3.jpg')
        return thumbnail
    
class LikedContent(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.content.title}'

class Grade(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True) #ถ้าไม่ได้ใช้ก็ลบ เท่านั้น
    
    def __str__(self):
        return self.name
    
class LearningArea(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True) #ถ้าไม่ได้ใช้ก็ลบ เท่านั้น
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comments')
    parent_content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(User, related_name="likedcomments", through="LikedComment")
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
        
    class Meta:
        ordering = ['-created']

    
class LikedComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.comment.body[:30]}'
        
class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replies')
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(User, related_name="likedreplies", through="LikedReply")
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
        
    class Meta:
        ordering = ['created']
        
        
class LikedReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.reply.body[:30]}'
    
class GalleryImage(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ImageField(upload_to='gallery/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image for {self.content.title}"

class RichTextContent(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, related_name='rich_text_content')
    rich_text = CKEditor5Field('เนื้อหา', null=True, blank=True, config_name='extends')

    def __str__(self):
        #return self.rich_text[:50]  # แสดงเนื้อหาบางส่วนเพื่อให้ดูง่าย
        return str(self.content.title)
    
class Video(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, related_name='video')
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()
    
    def __str__(self):
        return str(self.content.title)
    
    #felt cute might delete later
    class Meta:
        ordering = ['added']

class EBook(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    link = models.URLField(blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to='ebooks/', validators=[FileExtensionValidator(['pdf', 'epub', 'mobi', 'azw', 'azw3', 'doc', 'docx'])])
    author = models.CharField(null=True, blank=True, max_length=255)
    publication_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.content.title
    
class Project(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    # project_file = models.FileField(upload_to='projects/', validators=[FileExtensionValidator(['pdf'])], null=True)
    
    # Additional fields
    creators = models.CharField(max_length=255, null=True)  # Example: นาย ทศวิน จ้างประเสริฐ,นาย เหมชาติ เชื้อโชติ,นาย นิพัฒน์ จงเจริญศิริชื่อ
    advisor = models.CharField(max_length=255, null=True)  # Example: ดร. คมวุฒิ วิภูษิต
    institution = models.CharField(max_length=255, null=True)  # Example: สถาบันเทคโนโลยีนานาชาติสิรินธร มหาวิทยาลัยธรรมศาสตร์
    education_level = models.CharField(max_length=50, null=True)  # Example: ปริญญาโทขึ้นไป
    subject_category = models.CharField(max_length=100, null=True)  # Example: คอมพิวเตอร์
    completion_date = models.DateField(null=True)  # Example: 1 มกราคม 2541
    def __str__(self):
        return self.content.title
    
class ProjectFile(models.Model):
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='projects/', validators=[FileExtensionValidator(['pdf'])])

    def __str__(self):
        return f"{self.project.content.title} - {self.file.name}"
    
class Application(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    creator = models.CharField(max_length=255)
    link_playstore = models.URLField(blank=True, null=True)
    link_appstore = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return self.content.title
    
class PlanFile(models.Model):
    # content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    content = models.ForeignKey(Content, related_name='plan_files', on_delete=models.CASCADE )
    file = models.FileField(upload_to='teaching_plans/', validators=[FileExtensionValidator(['pdf','doc', 'docx'])], null=True, blank=True)

    def __str__(self):
        return f"{self.content.title} - {self.file.name}"
    
class SlideshowImage(models.Model):
    image = models.ImageField(upload_to='slideshow_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)
    order = models.PositiveIntegerField(default=0)
    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"Slideshow Image {self.id}"

templates/includes/header.html
{% load static %}
<header
    x-data="{ mobilenavOpen: false }"
    class="md:flex items-center justify-between [&>*]:px-8 bg-gray-800 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="/">
                <img class="w-10 -mt-1 mr-2" src="{% static 'images/book-open.svg' %}" />
                <span class="text-lg pridi-regular ">คลังสื่อดิจิทัล สพม.ปทุมธานี</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen"
                class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none"
                    src="https://img.icons8.com/small/64/ffffff/menu.png" />
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none"
                    src="https://img.icons8.com/small/64/ffffff/delete-sign.png" />
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak
        class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
        x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-96"
        x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            <li>
                <a href="{% url 'content-query' content_type='R' %}"
                    class="{% if content_type == 'R' or content_type == 'article' %}bg-gray-700 rounded-lg{% endif %}">
                    บทความ/บทเรียน
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='G' %}"
                    class="{% if content_type == 'G' or content_type == 'gallery' %}bg-gray-700 rounded-lg{% endif %}">
                    คลังภาพ
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='V' %}"
                    class="{% if content_type == 'V' or content_type == 'video' %}bg-gray-700 rounded-lg{% endif %}">
                    วิดีโอ
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='E' %}"
                    class="{% if content_type == 'E' or content_type == 'ebook' %}bg-gray-700 rounded-lg{% endif %}">
                    E-Book/Canva
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='P' %}"
                    class="{% if content_type == 'P' or content_type == 'project' %}bg-gray-700 rounded-lg{% endif %}">
                    โครงงาน
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='A' %}"
                    class="{% if content_type == 'A' or content_type == 'app' %}bg-gray-700 rounded-lg{% endif %}">
                    แอพพลิเคชั่น
                </a>
            </li>
            <li>
                <a href="{% url 'content-query' content_type='T' %}"
                    class="{% if content_type == 'T' or content_type == 'teaching_plan' %}bg-gray-700 rounded-lg{% endif %}">
                    แผนการสอน
                </a>
            </li>
            {% if user.is_authenticated %}
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false"
                    class="cursor-pointer select-none">
                    สร้างสื่อ
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4"
                        src="https://img.icons8.com/small/32/777777/expand-arrow.png" />
                </a>
                <div x-show="dropdownOpen" x-cloak
                    class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                    x-transition:enter="duration-300 ease-out"
                    x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                    x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="{% url 'content-create' content_type='article' %}">บทความ/บทเรียน</a></li>
                        <li><a href="{% url 'content-create' content_type='gallery' %}">คลังภาพ</a></li>
                        <li><a href="{% url 'content-create' content_type='video' %}">วิดีโอ</a></li>
                        <li><a href="{% url 'content-create' content_type='ebook' %}">E-Book/Canva</a></li>
                        <li><a href="{% url 'content-create' content_type='project' %}">โครงงาน</a></li>
                        <li><a href="{% url 'content-create' content_type='app' %}">แอพพลิเคชั่น</a></li>
                        <li><a href="{% url 'content-create' content_type='teaching_plan' %}">แผนการสอน</a></li>
                    </ul>
                </div>
            </li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false"
                    class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="{{ user.profile.avatar }}" />
                    {{ user.profile.name }}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4"
                        src="https://img.icons8.com/small/32/777777/expand-arrow.png" />
                </a>
                <div x-show="dropdownOpen" x-cloak
                    class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                    x-transition:enter="duration-300 ease-out"
                    x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                    x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="{% url 'profile' %}">โปรไฟล์ของฉัน</a></li>
                        <li><a href="{% url 'profile-edit' %}">แก้ไขโปรไฟล์</a></li>
                        <li><a href="{% url 'account_logout' %}">ออกจากระบบ</a></li>
                    </ul>
                </div>
            </li>
            {% else %}
            <li>
                <a href="{% url 'account_login' %}"
                    class="flex items-center gap-2 bg-blue-600 px-4 py-2 mx-2 rounded-lg hover:bg-blue-700 transition">
                    <img src="https://img.icons8.com/small/32/ffffff/login-rounded-right.png" class="w-6 h-6" />
                    เข้าสู่ระบบ
                </a>
            </li>
            <li>
                <a href="{% url 'account_signup' %}"
                    class="flex items-center gap-2 bg-green-600 px-4 py-2 rounded-lg hover:bg-green-700 transition">
                    <img src="https://img.icons8.com/small/32/ffffff/add-user-male.png" class="w-6 h-6" />
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/hero.html
{% load static %}
<hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('{% static 'images/lotus-background.jpg' %}')]">
  {% comment %} <div class="col-start-1 row-start-1 pb-4 px-8"> {% endcomment %}
  <div class="">
    <div class="max-w-6xl mx-auto my-4 px-6">
      <div class="card rounded-lg shadow-xl mx-auto">
        <div class="swiper-container">
          <div class="swiper-wrapper">
          {% if slideshow_images %}
            {% for image in slideshow_images %}
            <div class="swiper-slide">
              <img src="{{ image.image.url }}" alt="{{ image.caption }}" class="w-full h-80 object-cover"/>
            </div>
            {% endfor %}
          {% else %}
            <div class="swiper-slide">
              <img src="{% static 'images/catbook.jpg' %}" alt="" class="w-full h-80 object-cover"/>
            </div>
          {% endif %}
          </div>
          <!-- Add Pagination -->
          <div class="swiper-pagination"></div>
        </div>
      </div>
    </div>
  </div>
</hero>
<style>
  .card {
    padding-bottom: 0rem;
  }
</style>
<script>
  var swiper = new Swiper('.swiper-container', {
    loop: true,
    autoplay: {
      delay: 3000,
      disableOnInteraction: false,
    },
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
    },
  });
</script>

templates/includes/messages.html
{% if messages %}
<div x-data="{ showMessage: false }" >
{% for message in messages %}
<div x-cloak class="absolute mx-auto left-0 right-0 mt-2 max-w-xl z-50 flex items-center 
            {% if message.tags == 'error' %}bg-red-500{% else %}bg-amber-300{% endif %} text-white p-3 rounded-lg" role="alert"
    x-show="showMessage" 
    x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
    x-transition:enter="duration-700 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-5"
    x-transition:enter-end="opacity-100 translate-y-0"
    x-transition:leave="duration-200 ease-in"
    x-transition:leave-start="opacity-100 translate-y-0"
    x-transition:leave-end="opacity-0 -translate-y-5">
        <svg class="w-8 h-8 mr-2"  viewBox="0 0 512 512">
            <path d="M315.27,33,96,304H224L192.49,477.23a2.36,2.36,0,0,0,2.33,2.77h0a2.36,2.36,0,0,0,1.89-.95L416,208H288L319.66,34.75A2.45,2.45,0,0,0,317.22,32h0A2.42,2.42,0,0,0,315.27,33Z" style="fill:none;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px" fill="white"></path>
        </svg>
        <div>
            <div class="text-lg">{{ message }}</div>
        </div>
        <div class="ml-auto cursor-pointer" @click="showMessage = false">
            <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                <path d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </div>
    </div> 
{% endfor %}
</div>
{% endif %}

templates/includes/newer_old_hero.html
<!-- @format -->

<hero
  class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('https://live.staticflickr.com/65535/49909538937_3255dcf9e7_b.jpg')]">
  <div
    class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
  <div class="col-start-1 row-start-1 py-10 px-24">
    <div class="grid grid-cols-3 max-w-7xl mx-auto my-6 px-24 gap-x-8">
      <div class="card p-4 rounded-lg shadow-xl mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-4 text-black">ค้นหาสื่อ</h1>
        <form action="" method="GET">
          <div class="mt-4">
            <div class="flex items-center mb-2">
              <label for="types" class="mr-2 text-black">หมวดหมู่</label>
              <select
                name="type"
                class="rounded-md border border-gray-300 px-4 py-2 text-black">
                <option value="">ทั้งหมด</option>
                {% for type_value, type_label in type_choices %}
                <option value="{{ type_value }}">{{ type_label }}</option>
                {% endfor %}
              </select>
            </div>

            <div class="flex items-center mb-2">
              <label for="grades" class="mr-2 text-black">ชั้นเรียน</label>
              <select
                name="grade"
                class="rounded-md border border-gray-300 px-4 py-2 text-black">
                <option value="">ทั้งหมด</option>
                {% for grade in grades %}
                <option value="{{ grade.slug }}">{{ grade.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <button type="submit" class="mt-1">ค้นหา</button>
        </form>
      </div>
      <div
        class="card p-4 rounded-lg shadow-xl mx-auto px-4 py-8 col-span-2"></div>
    </div>
  </div>
</hero>

templates/includes/query_hero.html
{% load static %}
<hero
  class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('{% static 'images/lotus-background.jpg' %}')]">
  <div class="max-w-8xl mx-auto my-4 px-6">
    <form action="{% url 'content-query' content_type=content_type %}" method="GET" class="filter-form p-4 bg-gradient-to-r from-blue-800 to-gray-800 rounded-full shadow-md">
      <input type="hidden" name="content_type" value="{{ content_type }}">
      <div class="grid grid-cols-8 gap-1 pl-4 pr-4">
        <div class="col-span-3">
          {{ form.title }}
        </div>
        <div class="col-span-2">
          {{ form.grades__name }}
        </div>
        <div class="col-span-2">
          {{ form.learning_areas__name }}
        </div>
        <div>
          <button type="submit" class="rounded-full">
            ค้นหา
          </button>
        </div>
      </div>
      
    </form>
  </div>
</hero>

<style>
  .filter-form #id_grades,
.filter-form #id_learning_areas {
    /* Reset or adjust the styles here */
    margin-bottom: unset;
}

.filter-form #id_grades div,
.filter-form #id_learning_areas div {
    display: unset;
    margin-right: unset;
    width: 16em;
    padding: 0.9rem;
}

.filter-form #id_grades div label,
.filter-form #id_learning_areas div label {
    border-radius: unset;
    padding: unset;
    border: unset;
    width: unset;
    cursor: unset;
    user-select: unset;
}

.filter-form #id_grades input,
.filter-form #id_learning_areas input {
    display: unset;
}

.filter-form #id_grades label:has(input:checked),
.filter-form #id_learning_areas label:has(input:checked) {
    background-color: unset;
    color: unset;
    border: unset;
}

{% comment %} .filter-form .textarea,
.filter-form textarea,
.filter-form input {
    border-radius: unset;
    padding: unset;
    background-color: unset;
    width: 100%;
} {% endcomment %}

select {
  width: 95%;
  padding: 0.9rem;
}

#query-hero .button,
#query-hero button,
#query-hero [type="submit"],
#query-hero [type="button"] {
    all: unset; /* ล้างค่า CSS ทั้งหมด */
    /* กำหนดค่า CSS ใหม่ */
    display: inline-block;
    padding: 0.5rem 1rem;
    background-color: #1e40af;
    color: white;
    border-radius: 0.25rem;
    cursor: pointer;
}

#query-hero .button:hover,
#query-hero button:hover,
#query-hero [type="submit"]:hover,
#query-hero [type="button"]:hover {
    background-color: #1e3a8a;
}
</style>