a_core/urls.py
from django.contrib import admin
from django.urls import include, path
from a_contents.views import *

from django.conf import settings
from django.conf.urls.static import static

from a_users.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('content/type/<str:content_type>/', home_view, name='content-query'),
    # path('content/<str:content_type>/', content_query_view, name='content-query'),
    
    path('content/create/<str:content_type>/', content_create_view, name='content-create'),
    path('content/delete/<pk>/', content_delete_view, name='content-delete'),
    path('content/edit/<pk>/', content_edit_view, name='content-edit'),
    path('content/<pk>/', content_page_view, name='content'),
    path('content/<pk>/like', like_content, name='like-content'),
    path('content/download/<str:content_id>/', download_gallery_images, name='download-gallery-images'),
    path('comment/like/<pk>/', like_comment, name='like-comment'),
    path('reply/like/<pk>/', like_reply, name='like-reply'),
    
    path('profile/', profile_view, name='profile'),
    path('<str:username>/', profile_view, name='userprofile'),
    path('profile/edit/', profile_edit_view, name='profile-edit'),
    path('profile/delete/', profile_delete_view, name='profile-delete'),
    path('profile/onboarding/', profile_edit_view, name='profile-onboarding'),
    path('commentsent/<pk>/', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>/', comment_delete_view, name='comment-delete'),
    path('reply-sent/<pk>/', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>/', reply_delete_view, name='reply-delete'),
    
    #Ckeditor
    # path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="custom_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_contents/models.py
from django.db import models

from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from django.templatetags.static import static
import uuid

from embed_video.fields import EmbedVideoField
from django.core.validators import FileExtensionValidator


# Create your models here.
class Content(models.Model):
    class TypeChoices(models.TextChoices):
        VIDEO = 'V'
        GALLERY = 'G'
        ARTICLE = 'R'
        PROJECT = 'P'
        LESSON = 'L'
        EBOOK = 'E'
        APP = 'A'
        TEACHING_PLAN = 'T'
        
    class ApprovalStatus(models.TextChoices):
        PENDING = 'P', 'Pending'
        APPROVED = 'A', 'Approved'
        REJECTED = 'R', 'Rejected'
        
    title = models.CharField(max_length=500)
    type = models.CharField(max_length=1, choices=TypeChoices.choices)
    image = models.ImageField(upload_to='thumpnails/', null=True, blank=True) #ถ้าเชื่อได้ไวว่ามันเซฟไปที่มีเดียจริงๆก็ค่อยเป็นเป็น '/'
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='contents')
    description = models.TextField()
    
    likes = models.ManyToManyField(User, related_name="likecontents", through="LikedContent")
    view_count = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    grades = models.ManyToManyField('Grade')
    learning_areas = models.ManyToManyField('LearningArea')
    subject = models.CharField(max_length=500, null=True, blank=True)
    
    # Approval status field
    approval_status = models.CharField(max_length=1, choices=ApprovalStatus.choices, default=ApprovalStatus.PENDING)
    
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created']
        
    @property
    def thumbnail(self):
        try:
            thumbnail = self.image.url
        except:
            thumbnail = static('images/catbook3.jpg')
        return thumbnail
    
class LikedContent(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.content.title}'

class Grade(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True) #ถ้าไม่ได้ใช้ก็ลบ เท่านั้น
    
    def __str__(self):
        return self.name
    
class LearningArea(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True) #ถ้าไม่ได้ใช้ก็ลบ เท่านั้น
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comments')
    parent_content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(User, related_name="likedcomments", through="LikedComment")
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
        
    class Meta:
        ordering = ['-created']

    
class LikedComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.comment.body[:30]}'
        
class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replies')
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.CharField(max_length=150)
    likes = models.ManyToManyField(User, related_name="likedreplies", through="LikedReply")
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
        
    class Meta:
        ordering = ['created']
        
        
class LikedReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username}: {self.reply.body[:30]}'
    
class GalleryImage(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ImageField(upload_to='gallery/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image for {self.content.title}"

class RichTextContent(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, related_name='rich_text_content')
    rich_text = CKEditor5Field('เนื้อหา', null=True, blank=True, config_name='extends')

    def __str__(self):
        #return self.rich_text[:50]  # แสดงเนื้อหาบางส่วนเพื่อให้ดูง่าย
        return str(self.content.title)
    
class Video(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, related_name='video')
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()
    
    def __str__(self):
        return str(self.content.title)
    
    #felt cute might delete later
    class Meta:
        ordering = ['added']

class EBook(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    link = models.URLField(blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to='ebooks/', validators=[FileExtensionValidator(['pdf', 'epub', 'mobi', 'azw', 'azw3', 'doc', 'docx'])])
    author = models.CharField(null=True, blank=True, max_length=255)
    publication_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.content.title
    
class Project(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    # project_file = models.FileField(upload_to='projects/', validators=[FileExtensionValidator(['pdf'])], null=True)
    
    # Additional fields
    creators = models.CharField(max_length=255, null=True)  # Example: นาย ทศวิน จ้างประเสริฐ,นาย เหมชาติ เชื้อโชติ,นาย นิพัฒน์ จงเจริญศิริชื่อ
    advisor = models.CharField(max_length=255, null=True)  # Example: ดร. คมวุฒิ วิภูษิต
    institution = models.CharField(max_length=255, null=True)  # Example: สถาบันเทคโนโลยีนานาชาติสิรินธร มหาวิทยาลัยธรรมศาสตร์
    education_level = models.CharField(max_length=50, null=True)  # Example: ปริญญาโทขึ้นไป
    subject_category = models.CharField(max_length=100, null=True)  # Example: คอมพิวเตอร์
    completion_date = models.DateField(null=True)  # Example: 1 มกราคม 2541
    def __str__(self):
        return self.content.title
    
class ProjectFile(models.Model):
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='projects/', validators=[FileExtensionValidator(['pdf'])])

    def __str__(self):
        return f"{self.project.content.title} - {self.file.name}"
    
class Application(models.Model):
    content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    creator = models.CharField(max_length=255)
    link_playstore = models.URLField(blank=True, null=True)
    link_appstore = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return self.content.title
    
class PlanFile(models.Model):
    # content = models.OneToOneField(Content, on_delete=models.CASCADE, primary_key=True)
    content = models.ForeignKey(Content, related_name='plan_files', on_delete=models.CASCADE )
    file = models.FileField(upload_to='teaching_plans/', validators=[FileExtensionValidator(['pdf','doc', 'docx'])], null=True, blank=True)

    def __str__(self):
        return f"{self.content.title} - {self.file.name}"
    
class SlideshowImage(models.Model):
    image = models.ImageField(upload_to='slideshow_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)
    order = models.PositiveIntegerField(default=0)
    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"Slideshow Image {self.id}"

a_contents/forms.py
from django.forms import ModelForm, modelformset_factory
from django import forms
from django.core.exceptions import ValidationError
import re

from django_ckeditor_5.widgets import CKEditor5Widget

from django.conf import settings
from django.core.validators import FileExtensionValidator

from .models import *

class ContentMetaForm(ModelForm):
  def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.fields["description"].required = False
  class Meta:
    model = Content
    fields = '__all__'
    exclude = ['type','author','likes','comments', 'view_count', 'approval_status']
    labels = {
      "title": 'ชื่อเรื่อง *',
      "image": "ภาพหน้าปก",
      "description": "คำอธิบาย *",
      "grades": "ชั้นเรียน *",
      "learning_areas": "สาระการเรียนรู้ *",
      "subject": "ชื่อวิชา",
    }
    widgets = {
      'image' : forms.FileInput(),
      'description': forms.Textarea(attrs={'rows':3,'class': 'form-control', 'placeholder': 'รายละเอียด'}),
      "grades": forms.CheckboxSelectMultiple(),
      "learning_areas": forms.CheckboxSelectMultiple(),
    }
    
class RichTextContentForm(forms.ModelForm):
  class Meta:
    model = RichTextContent
    fields = ['rich_text']
    labels = {
      "rich_text": 'เนื้อหา *',
    }
    widgets = {
      "rich_text": CKEditor5Widget(attrs={"class": "django_ckeditor_5"}, config_name="extends"),
    }

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {"url": 'วิดีโอ *',}
        widgets = {
            'url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'ใส่ลิงก์วิดีโอ'})
        }
    def clean_video_url(self):
        video_url = self.cleaned_data['video_url']
        # Regular expression pattern for YouTube URL validation
        youtube_regex = r'^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$'
        if not re.match(youtube_regex, video_url):
            raise ValidationError("Invalid YouTube URL")
        return video_url
      
class EBookForm(forms.ModelForm):
    # publication_date = forms.DateField(
    #     widget=forms.DateInput(attrs={'type': 'month'}),
    #     input_formats=['%Y-%m'],
    #     label="วันที่เผยแพร่ *"
    # )
    class Meta:
        model = EBook
        fields = ['link', 'file', 'author']
        labels = {
        "link": 'ลิงก์ E-Book/Canva',
        "file": "ไฟล์ E-Book *",
        "author": "ผู้แต่ง *",
        }
    # class Meta:
    #     model = EBook
    #     fields = ['link']
    #     labels = {
    #     "link": 'ลิงก์ E-Book',
    #     }
        
class ProjectForm(forms.ModelForm):
  completion_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'month'}),
        input_formats=['%Y-%m'],
        label="ทำโครงงาน/วิจัยเมื่อ *"
    )
  class Meta:
    model = Project
    fields = [
    'creators', 
    'advisor', 
    'institution', 
    'education_level', 
    'subject_category', 
    'completion_date'
    ]
    labels = {
      "creators": 'ผู้จัดทำ *',
      "advisor": "อาจารย์ที่ปรึกษา *",
      "institution": "สถาบันการศึกษา *",
      "education_level": "ระดับชั้น *",
      "subject_category": "หมวดวิชา *",
    }
    
class AppForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['creator', 'link_playstore', 'link_appstore']
        labels = {
          "creators": 'ผู้จัดทำ *',
          "link_playstore": "ลิงก์ Playstore",
          "link_appstore": "ลิงก์ Appstore",
        }

class CommentCreateForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['body']
    widgets = {
      'body' : forms.TextInput(attrs={'placeholder': 'เขียนความคิดเห็น ...'})
    }
    labels = {
      'body': ''
    }

class ReplyCreateForm(ModelForm):
  class Meta:
    model = Reply
    fields = ['body']
    widgets = {
      'body' : forms.TextInput(attrs={'placeholder': 'เขียนการตอบกลับ ...', 'class':"!text-sm"})
    }
    labels = {
      'body': ''
    }

class UploadFileForm(forms.Form):
    upload = forms.FileField(
        validators=[
            FileExtensionValidator(
                getattr(
                    settings,
                    "CKEDITOR_5_UPLOAD_FILE_TYPES",
                    ['jpeg', 'jpg', 'png', 'gif', 'bmp', 'webp', 'tiff'],
                ),
            ),
        ],
    )

  

templates/a_contents/comment.html
{% load static %}
<comment class="card p-4 !mb-4">
  <div class="flex justify-between items-center">
    {% if comment.author %} 
      <a class="flex items-center gap-1 mb-2" href="{% url 'userprofile' comment.author.username %}">
          <img class="w-8 h-8 object-cover rounded-full" src="{{ comment.author.profile.avatar }}"> 
          <span class="font-bold hover:underline">{{ comment.author.profile.name }}</span>
          <span class="text-sm font-normal text-gray-400">@{{ comment.author.username }}</span>
      </a>
      {% else %}
      <div class="flex items-center gap-1 mb-4">
        <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.png' %}">
        <span class="text-gray-500">ไม่มีผู้สร้าง</span> 
      </div>
      {% endif %}
  </div>
  <p class="text-xl px-2">
      {{ comment.body }}
  </p>
  <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
      <a @click="repliesOpen = !repliesOpen" class="hover:underline cursor-pointer">
        {% if comment.replies.count or user.is_authenticated %}
          <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
              <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                  <path d="M24 22h-24l12-20z"/>
              </svg>
          </div>
        {% endif %} 
        {% if comment.replies.count %}
          การตอบกลับ
          <span id="repliescount-{{ comment.id }}" class="font-light text-gray-500 ml-1">{{ comment.replies.count }}</span>
        {% else %}
          {% if user.is_authenticated %}
          เพิ่มการตอบกลับ
          {% endif %}
        {% endif %}
      </a>
      <div class="flex items-center gap-4 [&>a:hover]:underline">
          {% include "snippets/likes_comment.html" %}
          {% if user.is_authenticated and comment.author == user %}
          <a href="{% url 'comment-delete' comment.id %}">ลบ</a>
          {% endif %}
      </div>

      <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">
        {% for reply in comment.replies.all %}
          {% include "a_contents/reply.html" %}
        {% endfor %}
        {% if user.is_authenticated %}
          <form class="replyform flex justify-between" autocomplete="off"
          hx-post="{% url 'reply-sent' comment.id %}" 
          hx-target="this" 
          hx-swap="outerHTML">
            {% csrf_token %}
            <div class="flex-grow">
              {{ replyform }}
            </div>
              <button class="block" type="submit">Submit</button>
          </form>
          {% endif %}
      </div>
  </div> 
</comment>

templates/a_contents/content_card_big.html
<!-- @format -->
{% load static %}
<div class="card relative">
  <figure class="overflow-hidden w-full h-48">
    <a href="{% url "content" content.id %}">
      <img
        src="{{ content.thumbnail }}"
        class="rounded-lg object-cover w-full h-full transform scale-100 hover:scale-110 transition-transform duration-300"
      />
    </a>
  </figure>
  
  {% if user.is_authenticated and user == content.author %}
  <div class="absolute top-0 left-0 p-4">
    
    <div class="flex">
      <!-- แสดงสถานะการอนุมัติ -->
      {% if content.approval_status == 'A' %}
      <span class="bg-green-500 text-white rounded-full px-3 py-1 text-xs font-semibold shadow-lg">เผยแพร่แล้ว</span>
      {% elif content.approval_status == 'P' %}
      <span class="bg-yellow-500 text-white rounded-full px-3 py-1 text-xs font-semibold shadow-lg">รอตรวจสอบ</span>
      {% elif content.approval_status == 'R' %}
      <span class="bg-red-500 text-white rounded-full px-3 py-1 text-xs font-semibold shadow-lg">ปฏิเสธการเผยแพร่</span>
      {% endif %}
    </div>
    
  </div>
  <div class="absolute top-0 right-0 p-4">
    
    <div class="flex bg-white rounded-full px-2 py-1 shadow-inner shadow-lg">
      <a href="{% url 'content-edit' content.id %}">
        <img class="object-cover h-6 mr-1 opacity-60" src="https://img.icons8.com/material-outlined/50/000000/edit.png" alt="Edit">
      </a>
      <a href="{% url 'content-delete' content.id %}">
        <img class="object-cover h-6 mr-1 opacity-60" src="https://img.icons8.com/material-outlined/50/000000/delete.png" alt="Delete">
      </a>
    </div>
    
  </div>
  {% endif %}

  <div class="p-3">
    <a href="{% url "content" content.id %}">
      <h3 class="font-bold text-lg mb-2">{{ content.title }}</h3>
    </a>
    <div class="flex items-center gap-2 text-sm mb-2 flex-wrap">
      <p class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">
        {{ content.get_type_display }}
      </p>
    </div>
    <div class="flex justify-between items-end">
      <div class="flex">
        <span class="text-gray-500">การเข้าชม:</span>
        <span class="font-bold ml-2">{{ content.view_count }}</span>
      </div>
      <div class="flex items-center gap-4 [&>a:hover]:underline">
        {% include "snippets/likes.html" %}
      </div>
    </div>
  </div>
</div>

templates/a_contents/content_create_ebook.html
<!-- @format -->

{% extends "layouts/b.html" %} {% block content %}
{% load static %}
<h1>สร้าง E-Book/Canva</h1>
<div class="card !p-8">
  <div class="text-center flex flex-col items-center m-5">
    <img id="thumbnail" class="h-40 object-cover rounded-xl mr-4" src="{% static 'images/catbook3.jpg' %}">
  </div>
  <form action="" method=POST class="form-control p-2"
  enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{ebook_form.as_p}}
    <button type="submit" class="mt-1">สร้างเนื้อหา</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">ยกเลิก</a>
  </form>
</div>


<script>
  // This updates the thumbnail
  const fileInput = document.querySelector('input[type="file"]')

  fileInput.addEventListener("change", (event) => {
    const file = event.target.files[0]
    const image = document.querySelector("#thumbnail")

    if (file && file.type.includes("image")) {
      const url = URL.createObjectURL(file)
      image.src = url
    }
  })
</script>
{% endblock %}

templates/a_contents/content_create_gallery.html
<!-- @format -->

{% extends "layouts/b.html" %} {% block content %} {% load static %}
<h1>สร้างคลังภาพ</h1>
<div class="card !p-8">
  <div class="text-center flex flex-col items-center m-5">
    <img
      id="thumbnail"
      class="h-40 object-cover rounded-xl mr-4"
      src="{% static 'images/catbook3.jpg' %}" />
  </div>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <div id="imagePreview" class="grid grid-cols-4 gap-4"></div>

    <div class="form-group mt-3">
      <label>อัพโหลดรูปภาพ *ควรมีขนาดไม่เกิน 5MB หรือมีความกว้างไม่เกิน 3000 พิกเซล และความสูงไม่เกิน 3000 พิกเซล*</label>
      <input required name="images" type="file" multiple class="form-control-file" id="imageInput">
    </div>
    <button type="submit" class="mt-1">Submit</button>
    <a
      class="button secondaryAction ml-1"
      href="{{ request.META.HTTP_REFERER }}">ยกเลิก
    </a>
  </form>
</div>

<script>
  // This updates the thumbnail
  const fileInput = document.querySelector('input[type="file"]')

  fileInput.addEventListener("change", (event) => {
    const file = event.target.files[0]
    const image = document.querySelector("#thumbnail")

    if (file && file.type.includes("image")) {
      const url = URL.createObjectURL(file)
      image.src = url
    }
  })
</script>
<script>
  //This update the gallery upload
  document.getElementById('imageInput').addEventListener('change', function() {
      const previewContainer = document.getElementById('imagePreview');
      previewContainer.innerHTML = ''; // Clear previous previews

      const files = this.files;
      if (files.length === 0) {
          return;
      }

      for (const file of files) {
          const reader = new FileReader();
          reader.onload = function(event) {
              const imgElement = document.createElement('img');
              imgElement.src = event.target.result;
              imgElement.className = 'rounded-lg object-cover h-48 w-full';
              previewContainer.appendChild(imgElement);
          }
          reader.readAsDataURL(file);
      }
  });
</script>
{% endblock %}

templates/a_contents/content_create_video.html
<!-- @format -->

{% extends "layouts/b.html" %} {% block content %}
{% load static %}
<h1>สร้างวิดีโอ</h1>
<div class="card !p-8">
  <form action="" method=POST class="form-control p-2"
  enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{video_form.as_p}}
    <button type="submit" class="mt-1">สร้างเนื้อหา</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">ยกเลิก</a>
  </form>
</div>
{% endblock %}

templates/a_contents/content_delete.html
{% extends "layouts/b.html" %} {% block content %}

<div class="md:flex items-center">
  <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">
    {% include 'a_contents/content_card_big.html' %}
  </div>
  <div>
      <h1>Delete Post</h1>
      <p class="mb-6">Are you sure you want to delete this post?</p>
      
      <form method='POST'>
          {% csrf_token %}
          <button type="submit">Confirm</button>
          <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
      </form>
  </div>
</div>
{% endblock %}

templates/a_contents/content_display_article.html
<!-- @format -->

{% load static %}
    <div>
      <div>{{ content.rich_text_content.rich_text|safe }}</div>
    </div>

templates/a_contents/content_display_ebook.html
<div class="mx-auto p-4">
  <div class="flex flex-col md:flex-row">
    <div class="md:w-1/3 flex-shrink-0">
      <img src="{{ content.thumbnail }}" alt="" class="w-full rounded-lg shadow-md">
    </div>
    <div class="md:ml-6 mt-4 md:mt-0">
      <p class="text-gray-600 mt-2">{{ content.description }}</p>
      {% comment %} <p class="text-gray-700 mt-2 "><span><span class="font-semibold mr-4">ผู้แต่ง:</span>{{ content.ebook.author }}</span></p>
      <p class="text-gray-700 mt-2"><span><span class="font-semibold mr-2">เผยแพร่เมื่อ:</span>
        {{ content.ebook.publication_date|date:"F " }}
        <span id="publication-year">
      </span>
      </p> {% endcomment %}
      <span>
      {% if content.ebook.link %}
      <a href="{{ content.ebook.link }}" target=”_blank” 
      class="inline-block ml-1 mt-4 px-4 py-2 bg-gray-600 text-white rounded-lg shadow-md hover:bg-gray-500">ดูบนเว็บไซต์</a>
      {% endif %}
      {% if content.ebook.file %}
      <a href="{{ content.ebook.file.url }}" target=”_blank” 
      class="inline-block ml-1 mt-4 px-4 py-2 bg-gray-600 text-white rounded-lg shadow-md hover:bg-gray-500">ดาวน์โหลดไฟล์</a>
      {% endif %}
    </span>
    </div>
  </div>
</div>
<script>
  beYear = 543 + Number({{ content.ebook.publication_date|date:"Y" }})
  document.getElementById('publication-year').textContent = beYear;
</script>

templates/a_contents/content_display_video.html
<!-- @format -->
{% load embed_video_tags %}
<div class="flex justify-center mb-5">
{% video content.video.url '854x480' %}
</div>
<div class="mt-1 mb-5 ml-2">
  {{ content.description }}
</div>